### PR TITLE
oh hello there

### PR DESCRIPTION
**Pull request by CelestialCrafter**

### CODE REVIEW

**Comment by Rexogamer** [comment]
No seriously what even is this

**Comment by CelestialCrafter** [comment]
i added some stuff and idk what i added andddddd i need to push this so i can git clone without using my wokr because ide mess up

**Comment by CelestialCrafter** [comment]
so just mer ge it

**Comment by Rexogamer** [comment]
but all undid was add a dependency and a error log by mistake

**Comment by CelestialCrafter** [comment]
and gimme write access

**Comment by CelestialCrafter** [comment]
wait what happened to the code

**Comment by Rexogamer** [comment]
I want to review everything going into master

**Comment by CelestialCrafter** [comment]
no u dont

**Comment by Rexogamer** [comment]
I do, to prevent any bad stuff getting in

**Pull request closed without merging**
