### PR TITLE
Fix compile errors in Node 14

### PR DESCRIPTION
**Pull request by Oxygemo**
Signed-off-by: Odyssey346 <alej0hio2007@gmail.com>

### CODE REVIEW

**Comment by Rexogamer** [comment]
It *wasn’t* but we might as well update.

**Comment by Oxygemo** [comment]
> It *wasn’t* but we might as well update. I can’t currently test but looks mostly good.

OpenSUSE moment?

**Comment by Rexogamer** [comment]
did it work fine on your machine

**Comment by Oxygemo** [comment]
no

**Comment by Rexogamer** [comment]
@CelestialCrafter we need to fix styles it seems

**Pull request merged**
